## Importing Libraries ##

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
# Importing data set 

df = pd.read_csv("Project 1 - Weather Dataset.csv")
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [48]:
df                            # Complete Dataset

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [49]:
df.shape                        # No. of rows and columns

(8784, 8)

In [50]:
df.dtypes                        # Datatypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [51]:
df['Date/Time'] = pd.to_datetime(df['Date/Time'])               # Converting Date/time datatype
df.dtypes

Date/Time           datetime64[ns]
Temp_C                     float64
Dew Point Temp_C           float64
Rel Hum_%                    int64
Wind Speed_km/h              int64
Visibility_km              float64
Press_kPa                  float64
Weather                     object
dtype: object

In [65]:
df['Weather'].unique()                        # Unique values

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [66]:
df.nunique()                    # Total number of unique values

Date/Time           8784
Temprature_C         533
Dew Point Temp_C     489
Humidity_%            83
Wind Speed_km/h       34
Visibility_km         24
Pressure_kPa         518
Weather               50
dtype: int64

- By this command we can find any unique value from the columns ..

In [67]:
df.count()                         # Checking for the null values

Date/Time           8784
Temprature_C        8784
Dew Point Temp_C    8784
Humidity_%          8784
Wind Speed_km/h     8784
Visibility_km       8784
Pressure_kPa        8784
Weather             8784
dtype: int64

In [68]:
df['Weather'].value_counts()                            # No of values of each

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Ice Pellets,Fog                 1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

### 1. Weather is clear

In [69]:
df.groupby('Weather').get_group('Clear')

,Date/Time,Temprature_C,Dew Point Temp_C,Humidity_%,Wind Speed_km/h,Visibility_km,Pressure_kPa,Weather
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,2012-01-05 18:00:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,2012-01-05 19:00:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,2012-01-05 20:00:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,2012-01-05 21:00:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,2012-12-26 06:00:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,2012-12-28 10:00:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,2012-12-29 01:00:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,2012-12-29 02:00:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

### 2. When wind speed is exactly 4 km/h..

In [70]:
df[df['Wind Speed_km/h'] == 4]

,Date/Time,Temprature_C,Dew Point Temp_C,Humidity_%,Wind Speed_km/h,Visibility_km,Pressure_kPa,Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,2012-01-05 00:00:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,2012-01-05 05:00:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,2012-01-07 02:00:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,2012-12-31 08:00:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,2012-12-31 09:00:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,2012-12-31 10:00:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,2012-12-31 12:00:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,2012-12-31 13:00:00,-4.6,-6.6,86,4,12.9,100.63,Snow

### 3. All the null values

In [71]:
df.isnull().sum()

Date/Time           0
Temprature_C        0
Dew Point Temp_C    0
Humidity_%          0
Wind Speed_km/h     0
Visibility_km       0
Pressure_kPa        0
Weather             0
dtype: int64

### 4. Renaming the columns

In [73]:
df.rename(columns={'Press_kPa': 'Pressure_kPa'}, inplace=True)            
df.rename(columns={'Temp_C': 'Temprature_C'}, inplace=True)
df.rename(columns={'Rel Hum_%': 'Humidity_%'}, inplace=True)
df.rename(columns={'Weather': 'Weather Condition'}, inplace=True)

In [76]:
df.head()

,Date/Time,Temprature_C,Dew Point Temp_C,Humidity_%,Wind Speed_km/h,Visibility_km,Pressure_kPa,Weather Condition
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

###  5. All instances when 'Snow' was recoreded

In [79]:
df[df['Weather Condition'].str.contains('Snow')]

,Date/Time,Temprature_C,Dew Point Temp_C,Humidity_%,Wind Speed_km/h,Visibility_km,Pressure_kPa,Weather Condition
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

### 6. All the instances when "Wind Speed is above 24 km/h" and "Visibility is 25 km"..

In [84]:
df[(df['Wind Speed_km/h'] > 24 ) & (df['Visibility_km'] == 25)]

,Date/Time,Temprature_C,Dew Point Temp_C,Humidity_%,Wind Speed_km/h,Visibility_km,Pressure_kPa,Weather Condition
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,2012-12-28 17:00:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,2012-12-30 17:00:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,2012-12-30 19:00:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,2012-12-30 23:00:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,2012-12-31 00:00:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

### 7.Mean value of each column against each "Weather Condition".

In [85]:
df.groupby('Weather Condition').mean()

,Date/Time,Temprature_C,Dew Point Temp_C,Humidity_%,Wind Speed_km/h,Visibility_km,Pressure_kPa
Weather Condition,,,,,,,
Clear,2012-06-25 18:03:12.760180992,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,2012-07-01 16:51:29.583333376,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,2012-09-17 15:00:00.000000000,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",2012-06-30 00:44:15.000000000,8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",2012-12-17 09:00:00.000000000,0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000
"Drizzle,Snow",2012-12-18 16:30:00.000000000,1.050000,0.150000,93.500000,14.000000,10.500000,100.890000
"Drizzle,Snow,Fog",2012-12-19 20:56:00.000000000,0.693333,0.120000,95.866667,15.533333,5.513333,99.281333
Fog,2012-06-24 21:08:00.000000000,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,2012-03-05 23:25:42.857142784,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
"Freezing Drizzle,Fog",2012-04-30 06:20:00.000000000,-2.533333,-4.183333,88.500000,17.000000,5.266667,100.441667
"Freezing Drizzle,Haze",2012-02-01 12:00:00.000000000,-5.433333,-8.000000,82.000000,10.333333,2.666667,100.316667
"Freezing Drizzle,Snow",2012-06-27 12:32:43.636363520,-5.109091,-7.072727,86.090909,16.272727,5.872727,100.520909
Freezing Fog,2012-02-22 06:45:00.000000000,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,2012-02-14 01:34:17.142857216,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
"Freezing Rain,Fog",2012-06-28 15:45:00.000000000,-2.225000,-3.750000,89.500000,15.500000,7.550000,99.945000
"Freezing Rain,Haze",2012-02-01 14:30:00.000000000,-4.900000,-7.450000,82.500000,7.500000,2.400000,100.375000
"Freezing Rain,Ice Pellets,Fog",2012-12-17 03:00:00.000000000,-2.600000,-3.700000,92.000000,28.000000,8.000000,100.950000
"Freezing Rain,Snow Grains",2012-01-13 09:00:00.000000000,-5.000000,-7.300000,84.000000,32.000000,4.800000,98.560000
Haze,2012-06-06 00:37:30.000000000,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,2012-07-12 06:48:08.888888832,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
"Moderate Rain,Fog",2012-12-10 08:00:00.000000000,1.700000,0.800000,94.000000,17.000000,6.400000,99.980000
Moderate Snow,2012-07-05 12:00:00.000000000,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
"Moderate Snow,Blowing Snow",2012-12-27 11:00:00.000000000,-5.450000,-6.500000,92.500000,40.000000,0.600000,100.570000
Mostly Cloudy,2012-07-01 10:42:53.417109760,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,2012-07-02 07:18:02.352941056,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,2012-07-14 17:25:51.063829760,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
"Rain Showers,Fog",2012-10-20 03:00:00.000000000,12.800000,12.100000,96.000000,13.000000,6.400000,99.830000
"Rain Showers,Snow Showers",2012-11-19 21:00:00.000000000,2.150000,-1.500000,76.500000,22.500000,21.700000,101.100000
"Rain,Fog",2012-08-17 05:19:08.275862016,8.273276,7.219828,93.189655,14.793103,6.873276,100.500862
"Rain,Haze",2012-03-13 08:00:00.000000000,4.633333,2.066667,83.333333,11.666667,6.700000,100.540000
"Rain,Ice Pellets",2012-12-18 05:00:00.000000000,0.600000,-0.600000,92.000000,24.000000,9.700000,100.120000
"Rain,Snow",2012-07-22 00:23:20.000000000,1.055556,-0.566667,89.000000,28.388889,11.672222,99.951111
"Rain,Snow Grains",2012-12-21 00:00:00.000000000,1.900000,-2.100000,75.000000,26.000000,25.000000,100.600000
"Rain,Snow,Fog",2012-12-08 21:00:00.000000000,0.800000,0.300000,96.000000,9.000000,6.400000,100.730000
"Rain,Snow,Ice Pellets",2012-12-21 03:15:00.000000000,1.100000,-0.175000,91.500000,23.250000,6.000000,100.105000
Snow,2012-04-18 19:10:36.923076864,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,2012-11-24 15:00:00.000000000,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,2012-07-21 22:40:59.999999744,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
"Snow Showers,Fog",2012-12-28 17:15:00.000000000,-10.675000,-11.900000,90.750000,13.750000,7.025000,101.292500
"Snow,Blowing Snow",2012-08-08 17:44:12.631578880,-5.410526,-7.621053,84.473684,34.842105,4.105263,99.704737
"Snow,Fog",2012-10-21 17:42:09.729729792,-5.075676,-6.364865,90.675676,17.324324,4.537838,100.688649
"Snow,Haze",2012-02-01 19:00:00.000000000,-4.020000,-6.860000,80.600000,5.000000,4.640000,100.782000
"Snow,Ice Pellets",2012-09-14 21:00:00.000000000,-1.883333,-3.666667,87.666667,23.833333,7.416667,100.548333
Thunderstorms,2012-07-10 08:30:00.000000000,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000
"Thunderstorms,Heavy Rain Showers",2012-05-29 06:00:00.000000000,10.900000,9.000000,88.000000,9.000000,2.400000,100.260000
"Thunderstorms,Moderate Rain Showers,Fog",2012-07-17 06:00:00.000000000,19.600000,18.500000,93.000000,15.000000,3.200000,100.010000
"Thunderstorms,Rain",2012-07-04 02:20:00.000000000,20.433333,18.533333,89.000000,15.666667,19.833333,100.420000
"Thunderstorms,Rain Showers",2012-07-18 14:48:45.000000000,20.037500,17.618750,86.375000,18.312500,15.893750,100.233750
"Thunderstorms,Rain Showers,Fog",2012-07-16 02:40:00.000000000,21.600000,18.700000,84.000000,19.666667,9.700000,100.063333
"Thunderstorms,Rain,Fog",2012-07-17 05:00:00.000000000,20.600000,18.600000,88.000000,19.000000,4.800000,100.080000

### 8. All instances when "Weather is Clear" and "Visibility is above 40"...

In [89]:
df[(df['Weather Condition'] == 'Clear') & (df['Visibility_km'] > 40)]

,Date/Time,Temprature_C,Dew Point Temp_C,Humidity_%,Wind Speed_km/h,Visibility_km,Pressure_kPa,Weather Condition
351,2012-01-15 15:00:00,-15.4,-22.8,53,24,48.3,102.71,Clear
352,2012-01-15 16:00:00,-15.1,-22.8,52,24,48.3,102.79,Clear
425,2012-01-18 17:00:00,-11.3,-18.8,54,26,48.3,101.54,Clear
440,2012-01-19 08:00:00,-13.7,-18.4,68,19,48.3,101.84,Clear
441,2012-01-19 09:00:00,-12.7,-17.2,69,17,48.3,101.73,Clear
...,...,...,...,...,...,...,...,...
8384,2012-12-15 08:00:00,-10.7,-15.6,67,13,48.3,102.69,Clear
8385,2012-12-15 09:00:00,-10.4,-15.9,64,19,48.3,102.74,Clear
8389,2012-12-15 13:00:00,-8.4,-14.7,60,19,48.3,102.64,Clear
8631,2012-12-25 15:00:00,-7.1,-13.7,59,17,48.3,101.98,Clear
8632,2012-12-25 16:00:00,-7.5,-13.9,60,11,48.3,102.03,Clear

### 9. All instances when "Weather is Clear" and "Relative Humidity is greater than 50"...

In [95]:
df[(df['Weather Condition'] == 'Clear') & (df['Humidity_%'] > 50) & (df['Visibility_km'] > 40)]

,Date/Time,Temprature_C,Dew Point Temp_C,Humidity_%,Wind Speed_km/h,Visibility_km,Pressure_kPa,Weather Condition
351,2012-01-15 15:00:00,-15.4,-22.8,53,24,48.3,102.71,Clear
352,2012-01-15 16:00:00,-15.1,-22.8,52,24,48.3,102.79,Clear
425,2012-01-18 17:00:00,-11.3,-18.8,54,26,48.3,101.54,Clear
440,2012-01-19 08:00:00,-13.7,-18.4,68,19,48.3,101.84,Clear
441,2012-01-19 09:00:00,-12.7,-17.2,69,17,48.3,101.73,Clear
...,...,...,...,...,...,...,...,...
8384,2012-12-15 08:00:00,-10.7,-15.6,67,13,48.3,102.69,Clear
8385,2012-12-15 09:00:00,-10.4,-15.9,64,19,48.3,102.74,Clear
8389,2012-12-15 13:00:00,-8.4,-14.7,60,19,48.3,102.64,Clear
8631,2012-12-25 15:00:00,-7.1,-13.7,59,17,48.3,101.98,Clear
8632,2012-12-25 16:00:00,-7.5,-13.9,60,11,48.3,102.03,Clear